[build]
  publish = "."

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/en/index.html"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/ru/index.html"
  to = "/ru/"
  status = 301

# Netlify's default behavior often handles clean URLs if enabled in the UI.
# If not, we will add manual redirects later.
